# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-10-02 08:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField(verbose_name='用户id')),
                ('gid', models.CharField(max_length=80, verbose_name='商品id')),
                ('gnum', models.IntegerField(verbose_name='商品数量')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='商品价格')),
                ('totalprice', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='商品总价格')),
            ],
            options={
                'db_table': 'tg_order',
            },
        ),
    ]
