# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-09-29 12:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tg_gu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=255, verbose_name='图片信息')),
            ],
            options={
                'db_table': 'tg_gu',
            },
        ),
        migrations.CreateModel(
            name='tg_hd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=255, verbose_name='图片信息')),
            ],
            options={
                'db_table': 'tg_hd',
            },
        ),
        migrations.CreateModel(
            name='tg_li',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=255, verbose_name='图片信息')),
            ],
            options={
                'db_table': 'tg_li',
            },
        ),
        migrations.CreateModel(
            name='tg_max',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=255, verbose_name='图片信息')),
            ],
            options={
                'db_table': 'tg_max',
            },
        ),
        migrations.CreateModel(
            name='tg_mid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=255, verbose_name='图片信息')),
            ],
            options={
                'db_table': 'tg_mid',
            },
        ),
        migrations.CreateModel(
            name='tg_min',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=255, verbose_name='图片信息')),
            ],
            options={
                'db_table': 'tg_min',
            },
        ),
        migrations.CreateModel(
            name='tg_pp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=255, verbose_name='图片信息')),
            ],
            options={
                'db_table': 'tg_pp',
            },
        ),
        migrations.CreateModel(
            name='tg_tg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=255, verbose_name='图片信息')),
            ],
            options={
                'db_table': 'tg_tg',
            },
        ),
        migrations.CreateModel(
            name='tg_zmgd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=255, verbose_name='图片信息')),
            ],
            options={
                'db_table': 'tg_zmgd',
            },
        ),
    ]
