# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-10-01 03:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='productid',
            field=models.CharField(max_length=100, verbose_name='商品编号'),
        ),
    ]
